### ISSUE TITLE
Issue with global organization token

### ISSUE THREAD

**Issue by midav7** [mend-toolkit/PS-Helicopter-Report#6]
Hi, I have added both organization token and my user key from Mend to config file, when I try running the jar it fails with the following error:

```
admin@macbook PS-Helicopter-Report % java -jar ./wss-helicopter-view-1.3.jar
===== Mend Helicopter View Report Generator =====
Sending API request - getAllOrganizations to: https://saas.mend.io/api/v1.4 CTX: 2d8f86c9493b2448183ef392fec43f1a91690548255538
Failed to execute getAllOrganizations. Got error code: 1007, error message: Invalid global organization token
Exit (-5)
```
I have double checked everything, my unified agent jar works with that org token, what might be the issue?

**Comment by clindseyws** [comment]
Hi midav7, please reach out to your CSM and they can arrange a call between the PS team that developed it and you.  They are going to need additional private key details that you do not want to share publicly.

**Comment by clindseyws** [comment]
Hi midav7, Toni will talk with you on your next touchpoint.  You are not using a Global Organization and this tool was written for reporting on a Global Organization level.  For a single organization, the Mend UI / Reports contain the same information that this tool provides.
